app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

/*
 * Las rutas existentes son: GET, POST, PUT, DELETE
 */

//RUTAS DEL FRONTEND
Route::get('/', [
    'uses' => 'FrontController@index',
    'as' => 'front.index',
]);

Route::get('categories/{name}', [
    'uses' => 'FrontController@searchCategory',
    'as' => 'front.search.category',
]);

Route::get('tags/{name}', [
    'uses' => 'FrontController@searchTag',
    'as' => 'front.search.tag',
]);

Route::get('articles/{slug}', [
    'uses' => 'FrontController@viewArticle',
    'as' => 'front.view.article',
]);

#Ruta normal
/*Route::get('articles', function () {
   echo "Esta es la sección de artículos";
});*/

#Ruta con paso de parámetros
/*Route::get('articles/{nombre}', function ($nombre) {
    echo "El nombre que has colocado es: " . $nombre;
});*/

#Ruta con parámetro opcional
/*Route::get('articles/{nombre?}', function ($nombre = "No coloco nombre") {
    echo "El nombre que has colocado es: " . $nombre;
});*/

#Grupo de rutas con prefijos
/*Route::group(['prefix' => 'articles'], function () {
    Route::get('view/{article?}', function ($article = "Vacío") {
        echo $article;
    });
    Route::get('view/{id}', [
        'uses'  =>  'TestController@view',
        'as'    =>  'articlesView'
    ]);
});*/

//RUTAS DEL PANEL DE ADMINISTRACIÓN
Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {
    /*
     * Con el método resource crea múltiples rutas para manejar una variedad de
     * acciones RESTful en el recurso del usuario. Del mismo modo, el controlador
     * generado ya tendrá métodos para cada una de estas acciones, incluidas notas
     * que le informan qué URI y verbos manejan.
     * https://laravel.com/docs/5.1/controllers#restful-resource-controllers
     */
    Route::get('/', [
        'as' => 'admin.index',
        function () {
            return view('admin.index');
        },
    ]);

    Route::group(['middleware' => 'admin'], function () {
        Route::resource('users', 'UsersController');
    });

    Route::resource('categories', 'CategoriesController');

    Route::resource('tags', 'TagsController');

    Route::resource('articles', 'ArticlesController');

    Route::get('images', [
        'uses' => 'ImagesController@index',
        'as' => 'admin.images.index',
    ]);
});

Route::group(['prefix' => 'admin/auth'], function () {
    Route::get('login', [
        'uses' => 'Auth\AuthController@getLogin',
        'as' => 'admin.auth.login',
    ]);
    Route::post('login', [
        'uses' => 'Auth\AuthController@postLogin',
        'as' => 'admin.auth.login',
    ]);
    Route::get('logout', [
        'uses' => 'Auth\AuthController@getLogout',
        'as' => 'admin.auth.logout',
    ]);
});

resources/views/admin/template/partials/errors.blade.php
@if(count($errors) > 0)
    <div class="alert alert-danger" role="alert">
        <h4>Por favor, corrige los siguientes errores:</h4>
        <ul>
            @foreach($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/admin/template/partials/footer.blade.php
<div class="panel panel-default">
    <div class="panel-footer">
        Todos los derechos reservados © 2018
        <span style="float: right">CodigoFacilito</span>
    </div>
</div>

resources/views/admin/template/partials/nav.blade.php
<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <!--Con esto creamos el boton para dispositivos moviles que contienen
            todas las secciones del menú, cada span es cada línea del dibujo.-->
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-1">
                <span class="sr-only">Menú</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <!--Aquí va el logo o nombre de la empresa-->
            <a href="{{ url('/') }}" class="navbar-brand">Empresas Noffra</a>
        </div>
        <div class="collapse navbar-collapse" id="navbar-1">
            @if(Auth::user())
                <ul class="nav navbar-nav">
                    <li><a href="{{ route('admin.index') }}">Inicio</a></li>
                    @if(Auth::user()->admin())
                        <li><a href="{{ route('admin.users.index') }}">Usuarios</a></li>
                    @endif
                    <li><a href="{{ route('admin.categories.index') }}">Categorías</a></li>
                    <li><a href="{{ route('admin.articles.index') }}">Artículos</a></li>
                    <li><a href="{{ route('admin.images.index') }}">Imágenes</a></li>
                    <li><a href="{{ route('admin.tags.index') }}">Tags</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{{ route('front.index') }}" target="_blank">Página principal</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">
                            {{ Auth::user()->name }} <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="{{ route('admin.auth.logout') }}">Salir</a></li>
                        </ul>
                    </li>
                </ul>
            @else
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{{ route('admin.auth.login') }}">Iniciar sesión</a></li>
                </ul>
            @endif
        </div>
    </div>
</nav>