app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

/*
 * Las rutas existentes son: GET, POST, PUT, DELETE
 */

//RUTAS DEL FRONTEND
Route::get('/', [
    'uses' => 'FrontController@index',
    'as' => 'front.index',
]);

Route::get('categories/{name}', [
    'uses' => 'FrontController@searchCategory',
    'as' => 'front.search.category',
]);

Route::get('tags/{name}', [
    'uses' => 'FrontController@searchTag',
    'as' => 'front.search.tag',
]);

Route::get('articles/{slug}', [
    'uses' => 'FrontController@viewArticle',
    'as' => 'front.view.article',
]);

#Ruta normal
/*Route::get('articles', function () {
   echo "Esta es la sección de artículos";
});*/

#Ruta con paso de parámetros
/*Route::get('articles/{nombre}', function ($nombre) {
    echo "El nombre que has colocado es: " . $nombre;
});*/

#Ruta con parámetro opcional
/*Route::get('articles/{nombre?}', function ($nombre = "No coloco nombre") {
    echo "El nombre que has colocado es: " . $nombre;
});*/

#Grupo de rutas con prefijos
/*Route::group(['prefix' => 'articles'], function () {
    Route::get('view/{article?}', function ($article = "Vacío") {
        echo $article;
    });
    Route::get('view/{id}', [
        'uses'  =>  'TestController@view',
        'as'    =>  'articlesView'
    ]);
});*/

//RUTAS DEL PANEL DE ADMINISTRACIÓN
Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {
    /*
     * Con el método resource crea múltiples rutas para manejar una variedad de
     * acciones RESTful en el recurso del usuario. Del mismo modo, el controlador
     * generado ya tendrá métodos para cada una de estas acciones, incluidas notas
     * que le informan qué URI y verbos manejan.
     * https://laravel.com/docs/5.1/controllers#restful-resource-controllers
     */
    Route::get('/', [
        'as' => 'admin.index',
        function () {
            return view('admin.index');
        },
    ]);

    Route::group(['middleware' => 'admin'], function () {
        Route::resource('users', 'UsersController');
    });

    Route::resource('categories', 'CategoriesController');

    Route::resource('tags', 'TagsController');

    Route::resource('articles', 'ArticlesController');

    Route::get('images', [
        'uses' => 'ImagesController@index',
        'as' => 'admin.images.index',
    ]);
});

Route::group(['prefix' => 'admin/auth'], function () {
    Route::get('login', [
        'uses' => 'Auth\AuthController@getLogin',
        'as' => 'admin.auth.login',
    ]);
    Route::post('login', [
        'uses' => 'Auth\AuthController@postLogin',
        'as' => 'admin.auth.login',
    ]);
    Route::get('logout', [
        'uses' => 'Auth\AuthController@getLogout',
        'as' => 'admin.auth.logout',
    ]);
});

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\SluggableInterface;
use Cviebrock\EloquentSluggable\SluggableTrait;

class Article extends Model implements SluggableInterface
{
    use SluggableTrait;

    protected $sluggable = [
        'build_from' => 'title',
        'save_to'    => 'slug'
    ];

    protected $table = "articles";

    protected $fillable = ['title', 'content', 'category_id', 'user_id'];

    #Cuando es singular significa que es solo a uno
    public function category()
    {
        return $this->belongsTo('\App\Category');
    }

    public function user()
    {
        return $this->belongsTo('\App\User');
    }

    public function images()
    {
        return $this->hasMany('\App\Image');
    }

    #Relación NxM
    public function tags()
    {
        return $this->belongsToMany('\App\Tag')->withTimestamps();
    }

    public function scopeSearch($query, $title)
    {
        return $query->where('title', 'LIKE', "%$title%");
    }
}

app/Http/Controllers/ArticlesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Category;
use App\Tag;
use App\Article;
use Illuminate\Support\Facades\Auth;
use App\Image;
use Laracasts\Flash\Flash;
use App\Http\Requests\ArticleRequest;

class ArticlesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $articles = Article::search($request->title)->orderBy('id', 'DESC')->paginate(5);
        //Al paginar, se debe usar este método para acceder a las relaciones
        $articles->each(function ($articles) {
            $articles->category;
            $articles->user;
        });

        return view('admin.articles.index', ['articles' => $articles]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //Esto sirve para los selectbox con laravelcollective
        $categories = Category::orderBy('name', 'ASC')->lists('name', 'id');
        //dd($categories);

        //En caso de no usar laravel collective, se debe hacer el recorrido de la siguiente manera
        //foreach ($categories as $field => $value) {
        //    echo $field . " y el nombre es " . $value . "<br>";
        //}
        //exit;
        $tags = Tag::orderBy('name', 'ASC')->lists('name', 'id');

        return view('admin.articles.create', ['categories' => $categories, 'tags' => $tags]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ArticleRequest $request)
    {
        //Manipulación de imágenes
        if ($request->file('image')) {
            $file = $request->file('image');
            $name = 'blogfacilito_' . time() . '.' . $file->getClientOriginalExtension();
            $path = public_path() . '/images/articles/';
            $file->move($path, $name);
        }

        $article = new Article($request->all());
        $article->user_id = Auth::user()->id;
        $article->save();

        if (isset($request->tags)) {
            $article->tags()->sync($request->tags);
        }

        $image = new Image();
        $image->name = $name;
        //Esto es válido también
        //$image->article_id = $article->id;
        $image->article()->associate($article);
        $image->save();

        Flash::success('Se ha creado el artículo ' . $article->title . ' de forma satisfactoria!');

        return redirect()->route('admin.articles.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $article = Article::find($id);
        $article->category;
        $categories = Category::orderBy('name', 'DESC')->lists('name', 'id');
        $tags = Tag::orderBy('name', 'ASC')->lists('name', 'id');

        /*
         * La etiqueta 'multiple' de html collective trabaja solamente con un array. Para ello,
         * buscamos todos los tags, los listamos y lo transformamos a un array con el método
         * proporcionado por laravel toArray()
         */
        $myTags = $article->tags->lists('id')->toArray();

        return view('admin.articles.edit', ['article' => $article, 'categories' => $categories, 'tags' => $tags, 'myTags' => $myTags]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $article = Article::find($id);
        $article->fill($request->all());
        $article->save();

        if (isset($request->tags)) {
            $article->tags()->sync($request->tags);
        }
        Flash::warning('Se ha editado el artículo ' . $article->title . ' de forma exitosa!');

        return redirect()->route('admin.articles.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $article = Article::find($id);
        $article->delete();

        Flash::error('Se ha borrado el artículo ' . $article->title . ' de forma exitosa!');
        return redirect()->route('admin.articles.index');
    }
}

resources/views/admin/articles/create.blade.php
@extends('admin.template.main')

@section('title', 'Agregar artículo')

@section('content')
    <div class="panel panel-default">
        <div class="panel-heading">Agregar artículo</div>
        <div class="panel-body">
            {!! Form::open(['route' => 'admin.articles.store', 'method' => 'POST', 'files' => true]) !!}
            <div class="form-group">
                {!! Form::label('title', 'Título') !!}
                {!! Form::text('title', null, ['class' => 'form-control', 'required', 'placeholder' => 'Título del artículo']) !!}
            </div>

            <div class="form-group">
                {!! Form::label('category_id', 'Categoría') !!}
                {!! Form::select('category_id', $categories, null, ['class' => 'form-control select-category', 'required']) !!}
            </div>

            <div class="form-group">
                {!! Form::label('content', 'Contenido') !!}
                {!! Form::textarea('content', null, ['class' => 'form-control textarea-content']) !!}
            </div>

            <div class="form-group">
                {!! Form::label('tags', 'Tags') !!}
                {!! Form::select('tags[]', $tags, null, ['class' => 'form-control select-tag', 'multiple']) !!}
            </div>

            <div class="form-group">
                {!! Form::label('image', 'Imágen') !!}
                {!! Form::file('image') !!}
            </div>

            <div class="form-group">
                {!! Form::submit('Agregar artículo', ['class' => 'btn btn-primary']) !!}
            </div>

            {!! Form::close() !!}
        </div>
    </div>
@endsection
@section('js')
    <script>
        $('.select-tag').chosen({
            placeholder_text_multiple: 'Seleccione un máximo de 3 tags',
            max_selected_options: 3,
            no_results_text: 'No se encontró este tag'
        });

        $('.select-category').chosen({
            placeholder_text_single: 'Seleccione una categoría',
            no_results_text: 'No se encontró esta categoría'
        });

        $('.textarea-content').trumbowyg();
    </script>
@endsection

resources/views/admin/articles/edit.blade.php
@extends('admin.template.main')

@section('title', 'Editar artículo ' . $article->title)

@section('content')
    <div class="panel panel-default">
        <div class="panel-heading">Editar artículo {{ $article->title }}</div>
        <div class="panel-body">
            {!! Form::open(['route' => ['admin.articles.update', $article->id], 'method' => 'PUT']) !!}
            <div class="form-group">
                {!! Form::label('title', 'Título') !!}
                {!! Form::text('title', $article->title, ['class' => 'form-control', 'required', 'placeholder' => 'Título del artículo']) !!}
            </div>

            <div class="form-group">
                {!! Form::label('category_id', 'Categoría') !!}
                {{-- También es válido usar $article->category_id --}}
                {!! Form::select('category_id', $categories, $article->category->id, ['class' => 'form-control select-category', 'required']) !!}
            </div>

            <div class="form-group">
                {!! Form::label('content', 'Contenido') !!}
                {!! Form::textarea('content', $article->content, ['class' => 'form-control textarea-content']) !!}
            </div>

            <div class="form-group">
                {!! Form::label('tags', 'Tags') !!}
                {!! Form::select('tags[]', $tags, $myTags, ['class' => 'form-control select-tag', 'multiple']) !!}
            </div>

            <div class="form-group">
                {!! Form::submit('Editar artículo', ['class' => 'btn btn-primary']) !!}
            </div>

            {!! Form::close() !!}
        </div>
    </div>
@endsection
@section('js')
    <script>
        $('.select-tag').chosen({
            placeholder_text_multiple: 'Seleccione un máximo de 3 tags',
            max_selected_options: 3,
            no_results_text: 'No se encontró este tag'
        });

        $('.select-category').chosen({
            placeholder_text_single: 'Seleccione una categoría',
            no_results_text: 'No se encontró esta categoría'
        });

        $('.textarea-content').trumbowyg();
    </script>
@endsection

resources/views/admin/articles/index.blade.php
@extends('admin.template.main')

@section('title', 'Listado de artículos')

@section('content')
    <div class="panel panel-default">
        <div class="panel-heading">Listado de artículos</div>
        <div class="panel-body">
            <a href="{{ route('admin.articles.create') }}" class="btn btn-info">Registrar nuevo artículo</a>
            {{--BUSCADOR DE ARTÍCULOS--}}
            {!! Form::open(['route' => 'admin.articles.index', 'method' => 'GET', 'class' => 'navbar-form pull-right']) !!}
            <div class="input-group">
                {!! Form::text('title', null, ['class' => 'form-control', 'placeholder' => 'Buscar artículo...', 'aria-describedby' => 'search']) !!}
                <span class="input-group-btn">
                    <button class="btn btn-primary" type="submit" id="search">
                        <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                    </button>
                </span>
            </div>
            {!! Form::close() !!}
            {{--FIN DEL BUSCADOR--}}
        </div>
        <!-- Table -->
        <table class="table">
            <thead>
            <th>ID</th>
            <th>Título</th>
            <th>Categoría</th>
            <th>Usuario</th>
            <th>Acción</th>
            </thead>
            <tbody>
            @foreach($articles as $article)
                <tr>
                    <td>{{ $article->id }}</td>
                    <td>{{ $article->title }}</td>
                    <td>{{ $article->category->name }}</td>
                    <td>{{ $article->user->name }}</td>
                    <td>
                        <form method="POST" action="{{ route("admin.articles.destroy", $article->id) }}">
                            {{ csrf_field() }}
                            {{ method_field('DELETE') }}
                            <a href="{{ route('admin.articles.edit', $article->id) }}" class="btn btn-warning"><span class="glyphicon glyphicon-wrench"></span></a>
                            <button type="submit" class="btn btn-danger" onclick="return confirm('¿Seguro que deseas eliminarlo?')"><span class="glyphicon glyphicon-remove-circle"></span></button>
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        <div class="text-center">
            {!! $articles->render() !!}
        </div>
    </div>
@endsection