app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

/*
 * Las rutas existentes son: GET, POST, PUT, DELETE
 */

//RUTAS DEL FRONTEND
Route::get('/', [
    'uses' => 'FrontController@index',
    'as' => 'front.index',
]);

Route::get('categories/{name}', [
    'uses' => 'FrontController@searchCategory',
    'as' => 'front.search.category',
]);

Route::get('tags/{name}', [
    'uses' => 'FrontController@searchTag',
    'as' => 'front.search.tag',
]);

Route::get('articles/{slug}', [
    'uses' => 'FrontController@viewArticle',
    'as' => 'front.view.article',
]);

#Ruta normal
/*Route::get('articles', function () {
   echo "Esta es la sección de artículos";
});*/

#Ruta con paso de parámetros
/*Route::get('articles/{nombre}', function ($nombre) {
    echo "El nombre que has colocado es: " . $nombre;
});*/

#Ruta con parámetro opcional
/*Route::get('articles/{nombre?}', function ($nombre = "No coloco nombre") {
    echo "El nombre que has colocado es: " . $nombre;
});*/

#Grupo de rutas con prefijos
/*Route::group(['prefix' => 'articles'], function () {
    Route::get('view/{article?}', function ($article = "Vacío") {
        echo $article;
    });
    Route::get('view/{id}', [
        'uses'  =>  'TestController@view',
        'as'    =>  'articlesView'
    ]);
});*/

//RUTAS DEL PANEL DE ADMINISTRACIÓN
Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {
    /*
     * Con el método resource crea múltiples rutas para manejar una variedad de
     * acciones RESTful en el recurso del usuario. Del mismo modo, el controlador
     * generado ya tendrá métodos para cada una de estas acciones, incluidas notas
     * que le informan qué URI y verbos manejan.
     * https://laravel.com/docs/5.1/controllers#restful-resource-controllers
     */
    Route::get('/', [
        'as' => 'admin.index',
        function () {
            return view('admin.index');
        },
    ]);

    Route::group(['middleware' => 'admin'], function () {
        Route::resource('users', 'UsersController');
    });

    Route::resource('categories', 'CategoriesController');

    Route::resource('tags', 'TagsController');

    Route::resource('articles', 'ArticlesController');

    Route::get('images', [
        'uses' => 'ImagesController@index',
        'as' => 'admin.images.index',
    ]);
});

Route::group(['prefix' => 'admin/auth'], function () {
    Route::get('login', [
        'uses' => 'Auth\AuthController@getLogin',
        'as' => 'admin.auth.login',
    ]);
    Route::post('login', [
        'uses' => 'Auth\AuthController@postLogin',
        'as' => 'admin.auth.login',
    ]);
    Route::get('logout', [
        'uses' => 'Auth\AuthController@getLogout',
        'as' => 'admin.auth.logout',
    ]);
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    #El primer atributo lleva el nombre de la tabla
    protected $table = "categories";

    #El atributo fillable son los campos permitidos para mostrar los objetos JSON, es decir,
    #con esto se mostrarán los campos que deseas de la BDD, en este ejemplo, solo name
    protected $fillable = ['name'];

    #Relación 1xN entre Categorias con Articulos
    #Cuando es plural significa que es muchos
    public function articles()
    {
        return $this->hasMany('App\Article');
    }

    public function scopeSearchCategory($query, $name)
    {
        return $query->where('name', '=', $name);
    }
}

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Http\Requests\CategoryRequest;
use App\Category;
use Laracasts\Flash\Flash;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::orderBy('id', 'DESC')->paginate(5);

        return view('admin.categories.index', ['categories' => $categories]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryRequest $request)
    {
        $category = new Category($request->all());
        $category->save();

        Flash::success('La categoría ' . $category->name . ' ha sido creada con éxito!');

        return redirect()->route('admin.categories.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::find($id);

        return view('admin.categories.edit', ['category' => $category]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $category = Category::find($id);
        $category->name = $request->name;
        $category->save();

        Flash::warning('La categoría ' . $category->name . ' ha sido editada con éxito!');

        return redirect()->route('admin.categories.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::find($id);
        $category->delete();

        Flash::error('La categoría ' . $category->name . ' ha sido borrada con éxito!');
        return redirect()->route('admin.categories.index');
    }
}

resources/views/admin/categories/create.blade.php
@extends('admin.template.main')

@section('title', 'Agregar categoría')

@section('content')
    <div class="panel panel-default">
        <div class="panel-heading">Agregar categoría</div>
        <div class="panel-body">
            {!! Form::open(['route' => 'admin.categories.store', 'method' => 'POST']) !!}
            <div class="form-group">
                {!! Form::label('name', 'Nombre') !!}
                {!! Form::text('name', null, ['class' => 'form-control', 'required', 'placeholder' => 'Nombre de la categoría']) !!}
            </div>

            <div class="form-group">
                {!! Form::submit('Registrar', ['class' => 'btn btn-primary']) !!}
            </div>

            {!! Form::close() !!}
        </div>
    </div>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('admin.template.main')

@section('title', 'Editar categoría ' . $category->name)

@section('content')
    <div class="panel panel-default">
        <div class="panel-heading">Editar categoría {{ $category->name }}</div>
        <div class="panel-body">
            {!! Form::open(['route' => ['admin.categories.update', $category->id], 'method' => 'PUT']) !!}
            <div class="form-group">
                {!! Form::label('name', 'Nombre') !!}
                {!! Form::text('name', $category->name, ['class' => 'form-control', 'required', 'placeholder' => 'Nombre de la categoría']) !!}
            </div>

            <div class="form-group">
                {!! Form::submit('Editar', ['class' => 'btn btn-primary']) !!}
            </div>

            {!! Form::close() !!}
        </div>
    </div>
@endsection

resources/views/admin/categories/index.blade.php
@extends('admin.template.main')

@section('title', 'Listado de categorías')

@section('content')
    <div class="panel panel-default">
        <div class="panel-heading">Listado de categorías</div>
        <div class="panel-body">
            <a href="{{ route('admin.categories.create') }}" class="btn btn-info">Registrar nueva categoría</a>
        </div>
        <!-- Table -->
        <table class="table">
            <thead>
            <th>ID</th>
            <th>Nombre</th>
            <th>Acción</th>
            </thead>
            <tbody>
            @foreach($categories as $category)
                <tr>
                    <td>{{ $category->id }}</td>
                    <td>{{ $category->name }}</td>
                    <td>
                        <form method="POST" action="{{ route("admin.categories.destroy", $category->id) }}">
                            {{ csrf_field() }}
                            {{ method_field('DELETE') }}
                            <a href="{{ route('admin.categories.edit', $category->id) }}" class="btn btn-warning"><span class="glyphicon glyphicon-wrench"></span></a>
                            <button type="submit" class="btn btn-danger" onclick="return confirm('¿Seguro que deseas eliminarlo?')"><span class="glyphicon glyphicon-remove-circle"></span></button>
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        <div class="text-center">
            {!! $categories->render() !!}
        </div>
    </div>
@endsection