app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

/*
 * Las rutas existentes son: GET, POST, PUT, DELETE
 */

//RUTAS DEL FRONTEND
Route::get('/', [
    'uses' => 'FrontController@index',
    'as' => 'front.index',
]);

Route::get('categories/{name}', [
    'uses' => 'FrontController@searchCategory',
    'as' => 'front.search.category',
]);

Route::get('tags/{name}', [
    'uses' => 'FrontController@searchTag',
    'as' => 'front.search.tag',
]);

Route::get('articles/{slug}', [
    'uses' => 'FrontController@viewArticle',
    'as' => 'front.view.article',
]);

#Ruta normal
/*Route::get('articles', function () {
   echo "Esta es la sección de artículos";
});*/

#Ruta con paso de parámetros
/*Route::get('articles/{nombre}', function ($nombre) {
    echo "El nombre que has colocado es: " . $nombre;
});*/

#Ruta con parámetro opcional
/*Route::get('articles/{nombre?}', function ($nombre = "No coloco nombre") {
    echo "El nombre que has colocado es: " . $nombre;
});*/

#Grupo de rutas con prefijos
/*Route::group(['prefix' => 'articles'], function () {
    Route::get('view/{article?}', function ($article = "Vacío") {
        echo $article;
    });
    Route::get('view/{id}', [
        'uses'  =>  'TestController@view',
        'as'    =>  'articlesView'
    ]);
});*/

//RUTAS DEL PANEL DE ADMINISTRACIÓN
Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {
    /*
     * Con el método resource crea múltiples rutas para manejar una variedad de
     * acciones RESTful en el recurso del usuario. Del mismo modo, el controlador
     * generado ya tendrá métodos para cada una de estas acciones, incluidas notas
     * que le informan qué URI y verbos manejan.
     * https://laravel.com/docs/5.1/controllers#restful-resource-controllers
     */
    Route::get('/', [
        'as' => 'admin.index',
        function () {
            return view('admin.index');
        },
    ]);

    Route::group(['middleware' => 'admin'], function () {
        Route::resource('users', 'UsersController');
    });

    Route::resource('categories', 'CategoriesController');

    Route::resource('tags', 'TagsController');

    Route::resource('articles', 'ArticlesController');

    Route::get('images', [
        'uses' => 'ImagesController@index',
        'as' => 'admin.images.index',
    ]);
});

Route::group(['prefix' => 'admin/auth'], function () {
    Route::get('login', [
        'uses' => 'Auth\AuthController@getLogin',
        'as' => 'admin.auth.login',
    ]);
    Route::post('login', [
        'uses' => 'Auth\AuthController@postLogin',
        'as' => 'admin.auth.login',
    ]);
    Route::get('logout', [
        'uses' => 'Auth\AuthController@getLogout',
        'as' => 'admin.auth.logout',
    ]);
});

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    protected $table = "tags";

    protected $fillable = ['name'];

    public function articles()
    {
        return $this->belongsToMany('\App\Article')->withTimestamps();
    }

    public function scopeSearch($query, $name)
    {
        return $query->where('name', 'LIKE', "%$name%");
    }

    public function scopeSearchTag($query, $name)
    {
        return $query->where('name', '=', $name);
    }
}

app/Http/Controllers/TagsController.php
<?php

namespace App\Http\Controllers;

use App\Tag;
use Illuminate\Http\Request;
use App\Http\Requests\TagRequest;
use Laracasts\Flash\Flash;
use App\Http\Requests;
use App\Http\Controllers\Controller;

class TagsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $tags = Tag::search($request->name)->orderBy('id', 'DESC')->paginate(5);

        return view('admin.tags.index', ['tags' => $tags]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.tags.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TagRequest $request)
    {
        $tag = new Tag($request->all());
        $tag->save();

        Flash::success("El tag " . $tag->name . " ha sido creado con éxito!");

        return redirect()->route('admin.tags.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $tag = Tag::find($id);

        return view('admin.tags.edit', ['tag' => $tag]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $tag = Tag::find($id);
        $tag->name = $request->name;
        $tag->save();

        Flash::warning('El tag ' . $tag->name . ' ha sido editado con éxito!');

        return redirect()->route('admin.tags.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $tag = Tag::find($id);
        $tag->delete();

        Flash::error('El tag ' . $tag->name . ' ha sido borrado!');
        return redirect()->route('admin.tags.index');
    }
}

resources/views/admin/tags/create.blade.php
@extends('admin.template.main')

@section('title', 'Agregar tag')

@section('content')
    <div class="panel panel-default">
        <div class="panel-heading">Agregar tag</div>
        <div class="panel-body">
            {!! Form::open(['route' => 'admin.tags.store', 'method' => 'POST']) !!}
            <div class="form-group">
                {!! Form::label('name', 'Nombre') !!}
                {!! Form::text('name', null, ['class' => 'form-control', 'required', 'placeholder' => 'Nombre del tag']) !!}
            </div>

            <div class="form-group">
                {!! Form::submit('Registrar', ['class' => 'btn btn-primary']) !!}
            </div>

            {!! Form::close() !!}
        </div>
    </div>
@endsection

resources/views/admin/tags/edit.blade.php
@extends('admin.template.main')

@section('title', 'Editar tag ' . $tag->name)

@section('content')
    <div class="panel panel-default">
        <div class="panel-heading">Editar tag {{ $tag->name }}</div>
        <div class="panel-body">
            {!! Form::open(['route' => ['admin.tags.update', $tag->id], 'method' => 'PUT']) !!}
            <div class="form-group">
                {!! Form::label('name', 'Nombre') !!}
                {!! Form::text('name', $tag->name, ['class' => 'form-control', 'required', 'placeholder' => 'Nombre del tag']) !!}
            </div>

            <div class="form-group">
                {!! Form::submit('Editar', ['class' => 'btn btn-primary']) !!}
            </div>

            {!! Form::close() !!}
        </div>
    </div>
@endsection

resources/views/admin/tags/index.blade.php
@extends('admin.template.main')

@section('title', 'Listado de tags')

@section('content')
    <div class="panel panel-default">
        <div class="panel-heading">Listado de tags</div>
        <div class="panel-body">
            <a href="{{ route('admin.tags.create') }}" class="btn btn-info">Registrar nuevo tag</a>
            {{--BUSCADOR DE TAGS--}}
            {!! Form::open(['route' => 'admin.tags.index', 'method' => 'GET', 'class' => 'navbar-form pull-right']) !!}
            <div class="input-group">
                {!! Form::text('name', null, ['class' => 'form-control', 'placeholder' => 'Buscar tag...', 'aria-describedby' => 'search']) !!}
                <span class="input-group-btn">
                    <button class="btn btn-primary" type="submit" id="search">
                        <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                    </button>
                </span>
            </div>
            {!! Form::close() !!}
            {{--FIN DEL BUSCADOR--}}
        </div>
        <!-- Table -->
        <table class="table">
            <thead>
            <th>ID</th>
            <th>Nombre</th>
            <th>Acción</th>
            </thead>
            <tbody>
            @foreach($tags as $tag)
                <tr>
                    <td>{{ $tag->id }}</td>
                    <td>{{ $tag->name }}</td>
                    <td>
                        <form method="POST" action="{{ route("admin.tags.destroy", $tag->id) }}">
                            {{ csrf_field() }}
                            {{ method_field('DELETE') }}
                            <a href="{{ route('admin.tags.edit', $tag->id) }}" class="btn btn-warning"><span
                                        class="glyphicon glyphicon-wrench"></span></a>
                            <button type="submit" class="btn btn-danger"
                                    onclick="return confirm('¿Seguro que deseas eliminarlo?')"><span
                                        class="glyphicon glyphicon-remove-circle"></span></button>
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        <div class="text-center">
            {!! $tags->render() !!}
        </div>
    </div>
@endsection